Green-Joy/BE

src/main/java/com/spring/GreenJoy/domain/post/PostController.java, src/main/java/com/spring/GreenJoy/domain/post/PostRepository.java, src/main/java/com/spring/GreenJoy/domain/post/PostService.java, src/main/java/com/spring/GreenJoy/domain/post/entity/Post.java, src/main/java/com/spring/GreenJoy/domain/user/UserRepository.java
- Post Entity 설계
- UserRepository의 JpaRepository 상속 수정
- Post Entity 설계
- UserRepository의 JpaRepository 상속 수정
=> feat: Post Entity 설계

.gitignore, build.gradle, src/main/java/com/spring/GreenJoy/config/FirebaseConfig.java, src/main/java/com/spring/GreenJoy/domain/post/PostController.java, src/main/java/com/spring/GreenJoy/domain/post/PostRepository.java, src/main/java/com/spring/GreenJoy/domain/post/PostService.java, src/main/java/com/spring/GreenJoy/domain/post/dto/CreateAndUpdatePostRequest.java, src/main/java/com/spring/GreenJoy/domain/post/dto/DeletePostRequest.java, src/main/java/com/spring/GreenJoy/domain/post/dto/GetPostListResponse.java, src/main/java/com/spring/GreenJoy/domain/post/dto/GetPostResponse.java, src/main/java/com/spring/GreenJoy/domain/post/entity/Post.java
- Post CRUD 구현(이미지 등록 구현X)
- `build.gradle`에 `Firebase` 의존성 추가, `.gitignore`에 `Firebase Key` 추가
- Post CRUD 구현(이미지 등록 구현X)
- `build.gradle`에 `Firebase` 의존성 추가, `.gitignore`에 `Firebase Key` 추가
=> feat: Post CRUD 구현(이미지 등록 구현X)

src/main/java/com/spring/GreenJoy/global/common/NanoId.java, src/main/java/com/spring/GreenJoy/global/dto/BaseResponse.java, src/main/java/com/spring/GreenJoy/global/exception/BaseException.java, src/main/java/com/spring/GreenJoy/global/exception/BaseResponseStatus.java
- BaseResponse, BaseException 추가
- BaseResponse, BaseException 추가 
- 선택 사항
=> feat: BaseResponse, BaseException 추가

src/main/java/com/spring/GreenJoy/domain/likes/Like.java, src/main/java/com/spring/GreenJoy/domain/likes/LikeController.java, src/main/java/com/spring/GreenJoy/domain/likes/LikeRepository.java, src/main/java/com/spring/GreenJoy/domain/likes/LikeService.java, src/main/java/com/spring/GreenJoy/domain/likes/dto/LikeRequest.java, src/main/java/com/spring/GreenJoy/domain/likes/entity/Like.java, src/main/java/com/spring/GreenJoy/domain/post/entity/Post.java
=> feat: 좋아요 기능 구현

src/main/java/com/spring/GreenJoy/config/WebMvcConfig.java
=> chore: CORS 설정

.gitignore, build.gradle, src/main/java/com/spring/GreenJoy/config/oauth/CustomOAuth2UserService.java, src/main/java/com/spring/GreenJoy/config/oauth/OAuthAttributes.java, src/main/java/com/spring/GreenJoy/config/security/SecurityConfig.java, src/main/java/com/spring/GreenJoy/domain/user/UserController.java, src/main/java/com/spring/GreenJoy/domain/user/UserRepository.java, src/main/java/com/spring/GreenJoy/domain/user/dto/CreateUserRequest.java, src/main/java/com/spring/GreenJoy/domain/user/dto/SessionUser.java, src/main/java/com/spring/GreenJoy/domain/user/entity/User.java, src/main/java/com/spring/GreenJoy/global/common/Role.java
- 구글 로그인(Spring Security + OAuth2.0) 구현
- 구글 로그인(Spring Security + OAuth2.0) 구현
- [스프링 시큐리티 - 구글 로그인](https://velog.io/@99mon/Spring-%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0-%EA%B5%AC%EA%B8%80-%EB%A1%9C%EA%B7%B8%EC%9D%B8)
- [Google OAuth 기능 구현](https://velog.io/@young224/Google-OAuth-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84)
=> feat: 구글 로그인(Spring Security + OAuth2.0) 구현

src/main/java/com/spring/GreenJoy/domain/comment/CommentController.java, src/main/java/com/spring/GreenJoy/domain/comment/CommentRepository.java, src/main/java/com/spring/GreenJoy/domain/comment/CommentService.java, src/main/java/com/spring/GreenJoy/domain/comment/dto/CreateCommentRequest.java, src/main/java/com/spring/GreenJoy/domain/comment/dto/DeleteCommentRequest.java, src/main/java/com/spring/GreenJoy/domain/comment/dto/GetCommentListResponse.java, src/main/java/com/spring/GreenJoy/domain/comment/dto/UpdateCommentRequest.java, src/main/java/com/spring/GreenJoy/domain/comment/entity/Comment.java
- Comment 기능 추가
- Comment 기능 추가
=> feat: Comment 기능 추가

src/main/java/com/spring/GreenJoy/domain/information/InformationController.java, src/main/java/com/spring/GreenJoy/domain/information/InformationRepository.java, src/main/java/com/spring/GreenJoy/domain/information/InformationService.java, src/main/java/com/spring/GreenJoy/domain/information/dto/CreateAndUpdateInfoRequest.java, src/main/java/com/spring/GreenJoy/domain/information/dto/GetInfoListResponse.java, src/main/java/com/spring/GreenJoy/domain/information/dto/GetInfoResponse.java, src/main/java/com/spring/GreenJoy/domain/information/entity/Information.java
- Information(꿀팁) 기능 추가
- Information(꿀팁) 기능 추가
- 피드, 꿀팁 삭제 할 때 작성한 유저인지 확인 등 에러 처리 필요
=> feat: Information(꿀팁) 기능 추가

src/main/java/com/spring/GreenJoy/domain/image/ImageService.java
- 이미지 저장 경로 수정(구글 클라우드 스토리지)
- 이미지 저장 경로 수정(구글 클라우드 스토리지)
=> fix: 이미지 버킷 저장 경로 수정

build.gradle, src/main/java/com/spring/GreenJoy/domain/article/ArticleController.java, src/main/java/com/spring/GreenJoy/domain/article/ArticleService.java, src/main/java/com/spring/GreenJoy/domain/article/dto/GetArticleResponse.java
- 뉴스 제공 기능 구현을 위한 크롤링 기능 구현
- 뉴스 제공 기능 구현을 위한 크롤링 기능 구현
- 이미지가 없는 뉴스는 불러오지 않도록 구현
- [Jsoup 활용한 네이버 뉴스 크롤링](https://velog.io/@person813/%ED%81%B4%EB%A6%B0-%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%94%84%EB%A7%81-resttemplate-Jsoup-%ED%99%9C%EC%9A%A9%ED%95%9C-%EB%84%A4%EC%9D%B4%EB%B2%84-%EB%89%B4%EC%8A%A4-%ED%81%AC%EB%A1%A4%EB%A7%81)
=> feat: Articles 크롤링 구현

src/main/java/com/spring/GreenJoy/domain/article/ArticleService.java, src/main/java/com/spring/GreenJoy/domain/article/dto/GetArticleResponse.java
- `Articles`에 미리보기 추가
- `Articles`에 미리보기 추가
=> fix: Articles 크롤링 DTO 수정

src/main/java/com/spring/GreenJoy/domain/post/PostController.java, src/main/java/com/spring/GreenJoy/domain/post/PostService.java, src/main/java/com/spring/GreenJoy/domain/user/UserRepository.java
- Post 삭제 시 유저 검증 기능 추가
- Post 삭제 시 유저 검증 기능 추가
=> fix: Post 삭제 시 유저 검증 기능 추가

src/main/java/com/spring/GreenJoy/domain/image/ImageService.java, src/main/java/com/spring/GreenJoy/domain/post/PostController.java, src/main/java/com/spring/GreenJoy/domain/post/PostService.java
- Google Cloud Storage에 저장된 이미지 삭제 구현
- Google Cloud Storage에 저장된 이미지 삭제 구현
=> feat: Google Cloud Storage에 저장된 이미지 삭제 구현

src/main/java/com/spring/GreenJoy/domain/post/PostController.java, src/main/java/com/spring/GreenJoy/domain/post/PostRepository.java, src/main/java/com/spring/GreenJoy/domain/post/PostService.java, src/main/java/com/spring/GreenJoy/domain/post/dto/CreateAndUpdatePostRequest.java, src/main/java/com/spring/GreenJoy/domain/post/dto/DeletePostRequest.java
=> refactor: 피드 로직 수정

src/main/java/com/spring/GreenJoy/domain/user/UserService.java
- 프론트엔드에서 Login 요청 시 받는 randomId를 정상적으로 받도록 수정
- 프론트엔드에서 Login 요청 시 받는 randomId를 정상적으로 받도록 수정
=> fix: 로그인 User 정보 반환 수정

src/main/java/com/spring/GreenJoy/domain/likes/LikeController.java, src/main/java/com/spring/GreenJoy/domain/likes/LikeService.java, src/main/java/com/spring/GreenJoy/domain/likes/dto/LikeRequest.java
=> refactor: 좋아요 유저 정보 수정

src/main/java/com/spring/GreenJoy/domain/information/InformationController.java, src/main/java/com/spring/GreenJoy/domain/information/InformationRepository.java, src/main/java/com/spring/GreenJoy/domain/information/InformationService.java, src/main/java/com/spring/GreenJoy/domain/information/dto/CreateAndUpdateInfoRequest.java, src/main/java/com/spring/GreenJoy/domain/information/dto/DeleteInfoRequest.java
- 꿀팁 유저 정보, 로직 수정
- 꿀팁 유저 정보, 로직 수정
=> refactor: 꿀팁 유저 정보, 로직 수정

src/main/java/com/spring/GreenJoy/domain/comment/CommentController.java, src/main/java/com/spring/GreenJoy/domain/comment/CommentRepository.java, src/main/java/com/spring/GreenJoy/domain/comment/CommentService.java, src/main/java/com/spring/GreenJoy/domain/comment/dto/CreateCommentRequest.java, src/main/java/com/spring/GreenJoy/domain/comment/dto/DeleteCommentRequest.java, src/main/java/com/spring/GreenJoy/domain/comment/dto/UpdateCommentRequest.java
- 댓글 유저 정보, 로직 수정
- 댓글 유저 정보, 로직 수정
=> refactor: 댓글 유저 정보, 로직 수정

src/main/java/com/spring/GreenJoy/domain/post/entity/Post.java
- Post ColumnDefault가 적용되도록 변경
- Post ColumnDefault가 적용되도록 변경
=> fix: Post ColumnDefault가 적용되도록 변경

src/main/java/com/spring/GreenJoy/domain/post/PostService.java, src/main/java/com/spring/GreenJoy/domain/post/dto/GetPostListResponse.java, src/main/java/com/spring/GreenJoy/domain/post/dto/GetPostResponse.java
=> refactor: 피드에 좋아요 수 표시

src/main/java/com/spring/GreenJoy/domain/challenge/ChallengeController.java, src/main/java/com/spring/GreenJoy/domain/challenge/ChallengeRepository.java, src/main/java/com/spring/GreenJoy/domain/challenge/ChallengeService.java
- 오늘의 챌린지 조회 추가
- 오늘의 챌린지 조회 추가
=> fix: challenge 기능 수정

src/main/java/com/spring/GreenJoy/domain/challenge/ChallengeRepository.java, src/main/java/com/spring/GreenJoy/domain/challenge/ChallengeService.java
- 챌린지 유저 정보, 로직 수정
- 챌린지 유저 정보, 로직 수정
=> refactor: challenge 유저 정보, 로직 수정

src/main/java/com/spring/GreenJoy/domain/challenge/entity/Challenge.java, src/main/java/com/spring/GreenJoy/domain/comment/entity/Comment.java, src/main/java/com/spring/GreenJoy/domain/information/entity/Information.java, src/main/java/com/spring/GreenJoy/domain/likes/entity/Like.java, src/main/java/com/spring/GreenJoy/domain/post/entity/Post.java
- Comment, Like에 cascade 추가
- Comment, Like에 cascade 추가
=> refactor: Comment, Like에 cascade 추가

src/main/java/com/spring/GreenJoy/domain/likes/entity/Like.java, src/main/java/com/spring/GreenJoy/domain/post/entity/Post.java, src/main/java/com/spring/GreenJoy/domain/user/UserService.java
- 연관관계 수정, 유저 프로필 이미지 기본값으로 구글 프로필 이미지 저장
- 연관관계 수정, 유저 프로필 이미지 기본값으로 구글 프로필 이미지 저장
=> refactor: 연관관계 수정, 유저 프로필 이미지 기본값으로 구글 프로필 이미지 저장

src/main/java/com/spring/GreenJoy/domain/post/PostService.java, src/main/java/com/spring/GreenJoy/domain/post/dto/GetPostListResponse.java
- 피드 페이징 조회시 프로필 이미지 전송
- 피드 페이징 조회시 프로필 이미지 전송
=> refactor: 피드 페이징 조회시 프로필 이미지 전송
